# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{easy-prof}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dmytro Shteflyuk"]
  s.date = %q{2010-02-23}
  s.description = %q{Simple Ruby code profiler to use both in Rails applications and generic Ruby scripts.}
  s.email = %q{kpumuk@kpumuk.info}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION.yml",
     "init.rb",
     "lib/easy_prof.rb",
     "lib/easy_profiler/action_controller_extensions.rb",
     "lib/easy_profiler/configuration.rb",
     "lib/easy_profiler/firebug_logger.rb",
     "lib/easy_profiler/no_profile_instance.rb",
     "lib/easy_profiler/profile.rb",
     "lib/easy_profiler/profile_instance.rb",
     "lib/easy_profiler/profile_instance_base.rb",
     "spec/easy_profiler_spec.rb",
     "spec/no_profile_instance_spec.rb",
     "spec/profile_instance_spec.rb",
     "spec/profile_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/kpumuk/easy-prof}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Simple and easy to use Ruby code profiler}
  s.test_files = [
    "spec/easy_profiler_spec.rb",
     "spec/no_profile_instance_spec.rb",
     "spec/profile_instance_spec.rb",
     "spec/profile_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

